version: '3'
services:
  allure:
    container_name: allure_test_mobile
    environment:
      TZ: "Europe/Samara"
    build:
      context: ${PWD}
      dockerfile: ./docker/allure-report/Dockerfile
    volumes:
      - ../allure-results:/var/allure-results/
    ports:
      - "35223:35223"
    command: sh -c "allure serve /var/allure-results --port 35223"
  python:
    container_name: pytest_test_mobile
    environment:
      TZ: "Europe/Samara"
    build:
      context: ${PWD}
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ../pyproject.toml:/var/pythonproject/pyproject.toml
      - ../README.md:/var/pythonproject/README.md
      - ../demowebshop:/var/pythonproject/demowebshop/
      - ../tests:/var/pythonproject/tests/
      - ../allure-results:/var/pythonproject/allure-results/
      - ../config.test.json:/var/pythonproject/config.test.json
    command: sh -c "google-chrome --version && poetry install && poetry run pytest tests/ --env=test --headless=true --attachments=false"
