version: '3'
services:
  allureTwo:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
      - "4040:4040"
    volumes:
      - ../allure-results:/app/allure-results
  python:
    environment:
      TZ: "Europe/Samara"
    build:
      context: ${PWD}
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ../pyproject.toml:/var/pythonproject/pyproject.toml
      - ../README.md:/var/pythonproject/README.md
      - ../demowebshop:/var/pythonproject/demowebshop/
      - ../tests:/var/pythonproject/tests/
      - ../allure-results:/var/pythonproject/allure-results/
      - ../config.test.json:/var/pythonproject/config.test.json
    command: sh -c "google-chrome --version && poetry install && poetry run pytest tests/ --env=test --headless=true --attachments=false"
